# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab3
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
end
